In [12]:
import numpy as np 

a = np.array([1, 2, 3, 4, 5, 7, 9, 11, 12])

b = a - 2

print (b)

mul = a * 6
print(mul)


exp = a ** 3   #double ** is exponent
print(exp)

greater_than_3 = a > 3
print(greater_than_3) 

[-1  0  1  2  3  5  7  9 10]
[ 6 12 18 24 30 42 54 66 72]
[   1    8   27   64  125  343  729 1331 1728]
[False False False  True  True  True  True  True  True]
