In [11]:
import numpy as np

# Create two matrices as 2D arrays
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[5, 6, 3], [2, 7, 8]])

# Matrix multiplication using np.matmul()
C = np.matmul(A, B)  # can also use @ operator to multiply matrices
print(C)

#for dot product

ab = np.array([1, 2, 7, 6])
bc = np.array([4, 5, 3, 4]) 

dot_product = np.dot(ab, bc)
print(dot_product)  



[[ 9 20 19]
 [23 46 41]
 [37 72 63]]
59
