In [30]:
import numpy as np


arr = np.array([
    [[1, 2, 3], [4, 5, 6],[3, 7, 1]],
    [[3, 4, 6], [2, 5, 9], [6, 4, 1]],
    [[1, 2, 3], [2, 4, 7], [4, 5, 8]]
    ])
 
print(arr[0][0], arr[1][0], arr[2][0])
cond = arr < 4
les4 = arr[cond]
print   (les4)
#random number generator
rand = np.random.default_rng()
print (rand.integers(10, size=(4,3)))
#unique values np.unique
leta = np.array ([1,1,1,3,3,3,55,55,32,11,23,32,32,23,5,5,7,8,10,10])
uniqval = np.unique (leta)
print (uniqval)
#reverse or flip the array
revleta = np.flip(leta)
print (revleta) # can also be done with 2D,3D,... array like
two_d = np.array (
    [[1,3,4],
    [2,1,1],
    [2,3,6],
    [4,7,2]]
)
revtwo = np.flip (two_d)
print (revtwo) 
#reshape
reshapetwo = np.reshape (two_d, (3,4))
print (reshapetwo)
tpose = reshapetwo.T #this is for transpose arr.transpose() can also be used
print (tpose)
#lets flatten array like flat earth into 1D lol
flat_arr = two_d.flatten()
print (flat_arr) #flatten dont change parent array while 'ravel' does change the parent array



[1 2 3] [3 4 6] [1 2 3]
[1 2 3 3 1 3 2 1 1 2 3 2]
[[6 5 8]
 [0 2 2]
 [1 8 3]
 [2 6 6]]
[ 1  3  5  7  8 10 11 23 32 55]
[10 10  8  7  5  5 23 32 32 23 11 32 55 55  3  3  3  1  1  1]
[[2 7 4]
 [6 3 2]
 [1 1 2]
 [4 3 1]]
[[1 3 4 2]
 [1 1 2 3]
 [6 4 7 2]]
[[1 1 6]
 [3 1 4]
 [4 2 7]
 [2 3 2]]
[1 3 4 2 1 1 2 3 6 4 7 2]
